import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "AI Chat Bot",
  description: "Generated by create next app",
  icons: {
    icon: "/chat-gpt-pfp.webp"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        {children}
        </body>
    </html>
  );
}
